version: "3.8"

services:
  database:
    image: "bitnami/postgresql"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todolist
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
